server:
  port: 8083
  servlet:
    context-root: auth-server

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: sa
    url: jdbc:h2:mem:customdb

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: getir-realm.json

logging:
  level:
    root: DEBUG
